### ISSUE TITLE
Is this project still alive?

### ISSUE THREAD

**Issue by wmarquardt** [sconts/kazam#56]
I've been using the Kazam application for a couple of months. I have some problems already reported in issues but it does not has a response or commit.  The last commits are from years ago and the software looks like it is losing compatibility with modern operating systems.

**Comment by konfou** [comment]
Note that Kazam upstream is at https://launchpad.net/kazam
The last update in unstable branch was two years ago https://code.launchpad.net/~kazam-team/kazam/unstable
@BigWhale could comment on status since he's mentioned as project's driver in Launchpad
There's also https://github.com/henrywoo/kazam-screen-recorder atop which the pip package is based on
And moreover, there's https://github.com/jlu5/kazam, which has a few bug fixes, and  https://github.com/deveee/kazam
The two previous also interestingly have the entire commit history (the former is a bit back)
